name: Deploy to Caprover
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  caprover-deploy:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: edrishn/weseeserver/wesee-server
          tags: ${{ github.sha }},latest
      - name: Deploy to Caprover
        uses: dankore/github-to-caprover@v.1.0.6
        with:
          server: "https://captain.rayvarz.link"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          appname: "wesee-server"
          image: docker.pkg.github.com/edrishn/weseeserver/wesee-server:${{ github.sha }}
